// Code generated by Arduino IoT Cloud: https://create.arduino.cc/iot/things

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "Device name obtained from things on Arduino IoT cloud";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onHeartRateChange();

int heart;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(heart, READWRITE, ON_CHANGE, onHeartRateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
